### ISSUE TITLE
Adding a CocoaPod in cordova-ios 4.3.0 makes build fail

### ISSUE THREAD

**Issue by R2D221** [Microsoft/remotebuild#10]
There's a new function in Cordova iOS where you can add CocoaPods from the config.xml file. This is fine and all, but the build fails on an unrelated note.

Adding a CocoaPod triggers an `event.emit('verbose', message)` call which ultimately leads to [logFormatHelper.ts to choose a format](https://github.com/Microsoft/remotebuild/blob/master/src/taco-utils/logFormatHelper.ts#L15) for the 'verbose' style. The problem is, there's no 'verbose' style, so the build fails with the error:

    TypeError colors[style] is not a function

The solution, of course, is to add the corresponding style.

**Comment by R2D221** [comment]
Just for the record, here's the full error log:

    Failed to install 'cordova-plugin-googlemaps':TypeError colors[style] is not a function (TaskId:9)
        at /Users/x/.taco_home/node_modules/taco-remote-lib/2.2.1/node_modules/taco-remote-lib/node_modules/taco-utils/logFormatHelper.js:143:44 (TaskId:9)
        at Array.forEach (native) (TaskId:9)
        at Function.LogFormatHelper.colorize (/Users/x/.taco_home/node_modules/taco-remote-lib/2.2.1/node_modules/taco-remote-lib/node_modules/taco-utils/logFormatHelper.js:141:24) (TaskId:9)
        at Function.LogFormatHelper.toFormattedString (/Users/x/.taco_home/node_modules/taco-remote-lib/2.2.1/node_modules/taco-remote-lib/node_modules/taco-utils/logFormatHelper.js:70:57) (TaskId:9)
        at EventEmitter.Logger.log (/Users/x/.taco_home/node_modules/taco-remote-lib/2.2.1/node_modules/taco-remote-lib/node_modules/taco-utils/logger.js:22:47) (TaskId:9)
        at emitOne (events.js:96:13) (TaskId:9)
        at EventEmitter.emit (events.js:188:7) (TaskId:9)
        at EventEmitter.module.exports.emit (/Users/x/.taco_home/node_modules/cordova/6.4.0/node_modules/cordova-common/src/events.js:71:17) (TaskId:9)
        at EventEmitter.module.exports.emit (/Users/x/.taco_home/remote-builds/taco-remote/builds/4912/cordovaApp/platforms/ios/cordova/node_modules/cordova-common/src/events.js:68:30) (TaskId:9)
        at /Users/x/.taco_home/remote-builds/taco-remote/builds/4912/cordovaApp/platforms/ios/cordova/Api.js:255:20 (TaskId:9)

**Comment by MSLaguana** [comment]
Thanks for the detailed report!

**Comment by psliurt** [comment]
Our team member also faced this issue.
He got the same error message while using the Visual Studio remote building feature.
But building on the mac, the building is smoothly and no error or exception.

Is there a solution to solve this issue?

It Seems that **logFormatHelper.js** has some problem!

**Comment by thegruffalo** [comment]
Is there an update on this, or is there a workaround. I opened this issue against the pushplugin. but it seems it's not a push plugin issus.
[https://github.com/phonegap/phonegap-plugin-push/issues/1502](https://github.com/phonegap/phonegap-plugin-push/issues/1502)

**Comment by allamgr** [comment]
@R2D221 How you fix this issue?

**Comment by MSLaguana** [comment]
We've just published an updated `taco-utils` package which should have a fix for this thanks to @powdernine. To get the fix, you will need to clear out `~/.taco_home/node-modules/taco-remote-lib`, then the next build you perform should download an updated version with the new taco-utils dependency.
