### ISSUE TITLE
unable to deploy or debug to the iOS device or simulator

### ISSUE THREAD

**Issue by Webrusterkk** [Microsoft/remotebuild#42]
After following this thread #26  , i'm able to  build the project and can able to generate the `.ipa` file using `LocalDevice` , but i'm unable to debug or Deploy directly to simulator or  device 

When i tried to debug using iOS Simulator i got the following error in Visual studio

```
----- Copying back to project: iOS
2>------ Deploy started: Project: TCM_Mobile, Configuration: Debug iOS ------
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 1 succeeded, 0 failed, 0 skipped ==========
```

But here is the Debug error

```
Timed out connecting debugger to remote Apache Cordova app. See Output window for JavaScript console output.
------ Cordova tools 6.5.0 already installed.
C:\Users\venkat\AppData\Roaming\npm\node_modules\vs-tac\node_modules\q\q.js:126
                    throw e;
                          ^
Error: The edge module has not been pre-compiled for node.js version v0.12.9. You must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge for building instructions.
    at determineVersion (C:\Users\venkat\AppData\Roaming\npm\node_modules\vs-tac\node_modules\edge\lib\edge.js:20:11)
    at Object.<anonymous> (C:\Users\venkat\AppData\Roaming\npm\node_modules\vs-tac\node_modules\edge\lib\edge.js:32:102)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\venkat\AppData\Roaming\npm\node_modules\vs-tac\lib\remoteBuild.js:19:12)
    at Module._compile (module.js:460:26)
------ Cordova tools 6.5.0 already installed.
C:\Users\venkat\AppData\Roaming\npm\node_modules\vs-tac\node_modules\q\q.js:126
                    throw e;
                          ^
Error: The edge module has not been pre-compiled for node.js version v0.12.9. You must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge for building instructions.
    at determineVersion (C:\Users\venkat\AppData\Roaming\npm\node_modules\vs-tac\node_modules\edge\lib\edge.js:20:11)
    at Object.<anonymous> (C:\Users\venkat\AppData\Roaming\npm\node_modules\vs-tac\node_modules\edge\lib\edge.js:32:102)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\venkat\AppData\Roaming\npm\node_modules\vs-tac\lib\remoteBuild.js:19:12)
    at Module._compile (module.js:460:26)
```

**Comment by Blatant** [comment]
Hi Webrusterkk, assuming your the same guy over on SE we meet again! 

Rather than add my own bug as a duplicate I'd like to add that I have also had this issue in the past, for me the remote build and deploy seem to work (I beleive I could open th remote project in XCode previously and run it natively) but the debug process just would not attach. 

If it helps with Webruster's case, you can find further details like lo files and such of my bug over on StaceExchange : https://stackoverflow.com/questions/40848096/vs2015-apache-cordova-ionic-debugging-on-remote-ios-simulator-fails?noredirect=1#comment76110042_40848096

**Comment by Webrusterkk** [comment]
@Blatant  , Yes i'm the same guy, checking for the solution for the problem and came to know that you are having the same issue, so i have raised it here , thanks for providing more info , so that this helps team to debug where issue is

**Comment by Blatant** [comment]
@Webrusterkk, no problem! The more info everyone has the easier it is to drill down to a solution in these strange cases. :) Did you ever get the project to transmit to the Mac? I found that once you found where remotebuild sent the project you could fire up xcode, load it and run/debug via Xcode and I seem to recall using that as a workaround (remotebuild->deploy, slide over to next desk and jump on the Mac, load XCode, debug Mac, slide back, apply changes in VS...).

**Comment by Webrusterkk** [comment]
@Blatant , As of now as a workaround i'm doing the same process .. It would be a pain but i'm living with it , should see it fixes the issue , so that's the reason  we are developing initially in android and later moving to the iOS , so that this solves the major problems..

**Comment by paymicro** [comment]
@Webrusterkk The bug is most likely in the old version of `node.js` on your Mac. Try to update `node.js` to actual stable version (6 or above).

**Comment by Webrusterkk** [comment]
@paymicro  thanks for the reply , I think i missed out to mention in my earlier post that i use the `node js 6.10.2` and npm latest and `cordova 6.5.0`

**Comment by paymicro** [comment]
@Webrusterkk, please provide additional information:
- `Visual Studio` version
- `node js` version on Windows

Try to remove [Cordova CLI pre-processor](https://taco.visualstudio.com/en-us/docs/configure-vs-tools-apache-cordova/#vstac)

**Comment by drewgillies** [comment]
Have just added label to indicate that this is a departure from the curated npm packages shipped with VS 2017 (i.e. cordova 6.5.0 instead of cordova 6.3.1). There may still be opportunities to support the scenario, but it's not one we have tested and support in general.

**Comment by Webrusterkk** [comment]
@drewgillies  thanks for the reply , but with `cordova 6.3.1` i'm unable to build the project targeting  `Xcode 8.3.2`   

@paymicro  `Visual studio - 2015 , node js : 6.10.2 , cordova : 6.5.0 , macos :  10.12`
