### ISSUE TITLE
Internal Server Error to Deploy to device after Build Succeed 

### ISSUE THREAD

**Issue by stephio** [Microsoft/remotebuild#55]
Hello to everyone.

I have a similar issue as one of the guys had in this post, but in my case the Build succeeds while the Deploy is giving an Internal Server error.

GET /cordova/build/4984/deploy 500 9.239 ms - 124
/usr/local/npm_packages/lib/node_modules/remotebuild/node_modules/applicationinsights/AutoCollection/Exceptions.js:25
throw error;
^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
at validateHeader (_http_outgoing.js:503:11)
at ServerResponse.setHeader (_http_outgoing.js:510:3)
at ServerResponse.header (/usr/local/npm_packages/lib/node_modules/remotebuild/node_modules/express/lib/response.js:700:10)
at ServerResponse.send (/usr/local/npm_packages/lib/node_modules/remotebuild/node_modules/express/lib/response.js:154:12)
at ServerResponse.json (/usr/local/npm_packages/lib/node_modules/remotebuild/node_modules/express/lib/response.js:240:15)
at ChildProcess. (/Users/steph/.taco_home/node_modules/taco-remote-lib/2.3.2/node_modules/taco-remote-lib/ios/ios.js:219:33)
at ChildProcess.emit (events.js:160:13)
at maybeClose (internal/child_process.js:943:16)
at Socket.stream.socket.on (internal/child_process.js:363:11)
at Socket.emit (events.js:160:13)

![image](https://user-images.githubusercontent.com/2204093/35737852-9fa1c78e-0835-11e8-851f-ccf2659c9355.png)

Any help would be appreciated!
Thanks!

**Comment by marcxploit** [comment]
Hi, I have the same problem too and I can't fixt it, could you fix it?
