### ISSUE TITLE
Error running remotebuild

### ISSUE THREAD

**Issue by gubyy** [Microsoft/remotebuild#7]
After updating my Mac I am running into an error when trying to run remote build from terminal. Here is the output:

remotebuild --secure false
/usr/local/lib/node_modules/remotebuild/node_modules/taco-utils/node_modules/applicationinsights/AutoCollection/Exceptions.js:25
                    throw error;
                    ^

Error: Error parsing your JSON configuration file: [/Users/developer/.taco_home/RemoteBuild.config].
    at File.loadSync (/usr/local/lib/node_modules/remotebuild/node_modules/nconf/lib/nconf/stores/file.js:141:13)
    at Provider.add (/usr/local/lib/node_modules/remotebuild/node_modules/nconf/lib/nconf/provider.js:135:23)
    at Provider.file (/usr/local/lib/node_modules/remotebuild/node_modules/nconf/lib/nconf/provider.js:61:15)
    at Function.CliHelper.parseRemoteBuildConf (/usr/local/lib/node_modules/remotebuild/lib/cli.js:65:15)
    at /usr/local/lib/node_modules/remotebuild/lib/cli.js:36:41
    at _fulfilled (/usr/local/lib/node_modules/remotebuild/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/remotebuild/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/remotebuild/node_modules/taco-utils/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/remotebuild/node_modules/taco-utils/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/remotebuild/node_modules/taco-utils/node_modules/q/q.js:137:13)

I have tried uninstalling remotebuild and reinstalling it with no success. Any idea on how to fix this?

**Comment by MSLaguana** [comment]
It sounds like you have a corrupted configuration file. Could you please look at `~/.taco_home/RemoteBuild.config` and see if it is valid JSON? You could also delete that file which will cause it to revert to defaults.

**Comment by gubyy** [comment]
@MSLaguana Thank you, deleting it fixed it.
